services:
  - type: web
    name: timetable-frontend
    env: static
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://timetable-5.onrender.com
