services:
  - type: static
    name: timetable-frontend
    env: static
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://timetable-5.onrender.com
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
